### ISSUE TITLE
Rococo Faucet is broken

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/substrate-matrix-faucet#123]
Since Rococo v2.1 relaunch, the Rococo faucet has been broken, it throws this error on startup:

```
[2022-03-16T09:28:51.507] [INFO] default - 🤖 Beep bop - Creating the bot's account
[2022-03-16T09:28:51.513] [INFO] default - ✓ FAUCET_ACCOUNT_MNEMONIC it set (secret)
[2022-03-16T09:28:51.513] [INFO] default - ◉ Optionnal environment variable FAUCET_BALANCE_CAP not set, using default (100).
[2022-03-16T09:28:51.513] [INFO] default - ✓ INJECTED_TYPES set to {}
[2022-03-16T09:28:51.514] [INFO] default - ✓ NETWORK_DECIMALS set to 12
[2022-03-16T09:28:51.514] [INFO] default - ✓ PORT set to 5555
[2022-03-16T09:28:51.514] [INFO] default - ✓ RPC_ENDPOINT set to https://rococo-rpc.polkadot.io/
[2022-03-16T09:28:51.514] [INFO] default - ------------------------------------------
[2022-03-16T09:28:51.515] [INFO] default - Starting faucet v1.1.2
[2022-03-16T09:28:51.522] [INFO] default - Faucet backend listening on port 5555.
2022-03-16 09:28:54        API/INIT: RPC methods not decorated: beefy_getFinalizedHead
2022-03-16 09:29:30        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: [521]: undefined
[2022-03-16T09:29:30.495] [ERROR] default - Error: [521]: undefined
    at assert (/backend/node_modules/@polkadot/util/assert.cjs:37:11)
    at HttpProvider._send2 (/backend/node_modules/@polkadot/rpc-provider/http/index.cjs:196:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async callWithRegistry (/backend/node_modules/@polkadot/rpc-core/bundle.cjs:261:22)
2022-03-16 09:32:51        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: [521]: undefined
```

**Comment by chevdor** [comment]
The PolkadotJS API is now [a bit old](https://github.com/paritytech/substrate-matrix-faucet/blob/main/package.json#L35) and could use a bump too.

**Comment by PierreBesson** [comment]
It looks like the faucet fixed itself magically yesterday:

```
2022-03-16 14:15:52        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: [521]: undefined
Error: [521]: undefined
    at assert (/backend/node_modules/@polkadot/util/assert.cjs:37:11)
    at HttpProvider._send2 (/backend/node_modules/@polkadot/rpc-provider/http/index.cjs:196:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async callWithRegistry (/backend/node_modules/@polkadot/rpc-core/bundle.cjs:261:22)
[2022-03-16T18:43:13.044] [INFO] default - 💸 sending tokens
```
