### ISSUE TITLE
The transaction has too low priority to replace another transaction already in the pool.

### ISSUE THREAD

**Issue by Tbaut** [paritytech/substrate-matrix-faucet#2]
from https://github.com/paritytech/devops/issues/664#issuecomment-721078538
the canvas-faucet just died with this (unhandled) exception in the server code:

```bash
Faucet backend listening on port 5555.
2020-11-03 02:02:15        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1014: Priority is too low: (2767803044496 vs 2767803044496): The transaction has too low priority to replace another transaction already in the pool.
(node:26) UnhandledPromiseRejectionWarning: Error: 1014: Priority is too low: (2767803044496 vs 2767803044496): The transaction has too low priority to replace another transaction already in the pool.
    at RpcCoder._checkError (/server/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)
    at RpcCoder.decodeResponse (/server/node_modules/@polkadot/rpc-provider/coder/index.js:47:10)
    at WsProvider.value (/server/node_modules/@polkadot/rpc-provider/ws/Provider.js:215:90)
    at W3CWebSocket.value [as onmessage] (/server/node_modules/@polkadot/rpc-provider/ws/Provider.js:195:153)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/server/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/server/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/server/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at WebSocketConnection.emit (events.js:189:13)
    at WebSocketConnection.processFrame (/server/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /server/node_modules/websocket/lib/WebSocketConnection.js:323:40
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Tbaut** [comment]
This looks like a race condition with 2 transaction with the same nonce in the tx pool. There should be a better nonce handling.

**Comment by Tbaut** [comment]
This is closed by https://github.com/paritytech/substrate-matrix-faucet/pull/37
if there's only 1 drip allowed per day, no race condition problem :nerd_face:
