### ISSUE TITLE
Unable to teleport funds on Westend faucet bot

### ISSUE THREAD

**Issue by bakhtin** [paritytech/substrate-matrix-faucet#224]
I'm getting an error when trying to teleport funds to an account on Westend Collectives parachain. I'm using [Westend faucet bot](https://matrix.to/#/#westend-devops:parity.io).
```
!drip 15zAuboGaAom3e4sA4dRgKokDbkcwSdGkSMjnaptrWX6RY7Y:1001
```
results in error:
```
[2023-03-08T13:08:26.069] [INFO] default - 💸 teleporting tokens
[2023-03-08T13:08:26.079] [ERROR] default - ⭕ An error occured when sending tokens Error: createType(XcmVersionedMultiLocation):: Cannot map Enum JSON, unable to find 'V1' in v2, v3
    at createTypeUnsafe (/backend/node_modules/@polkadot/types-create/cjs/create/type.js:73:18)
    at TypeRegistry.createTypeUnsafe (/backend/node_modules/@polkadot/types/cjs/create/registry.js:323:46)
    at TypeRegistry.createType (/backend/node_modules/@polkadot/types/cjs/create/registry.js:315:17)
    at ApiPromise.createType (/backend/node_modules/@polkadot/api/cjs/base/Decorate.js:122:27)
    at Actions.teleportTokens (/backend/build/src/server/services/Actions.js:103:66)
    at Actions.sendTokens (/backend/build/src/server/services/Actions.js:165:37)
    at /backend/build/src/server/routes/actions.js:45:62
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by PierreBesson** [comment]
It looks like this is also affecting Rococo now so this is high priority.

**Comment by PierreBesson** [comment]
See also the same issue on polkadot.js apps: https://github.com/polkadot-js/apps/issues/9127

**Comment by PierreBesson** [comment]
Found on the Rococo faucet room:

query:
```
!drip 5Gc1RWvH2MtDYB7NKrMEuMsVTMApG3rCjYjPpYvZ8yh2yD3X:1002
```

response:
```
createType(XcmVersionedMultiLocation):: Cannot map Enum JSON, unable to find 'V1' in v2, v3
````

**Comment by Bullrich** [comment]
Thanks for the input. If you have any more information that could be helpful please post it here.

@rzadp has created #225 to reproduce the issue

**Comment by PierreBesson** [comment]
The solution to this issue is to rewrite the [faucet Teleport code](https://github.com/paritytech/substrate-matrix-faucet/blob/0c54a08063f1d11376b09564f4c3a9d0cbab6742/src/dripper/polkadot/PolkadotActions.ts#L104-L144) to use XCM V3. I think V3 should be fully supported by all our testnet chains by now.

**Comment by Bullrich** [comment]
Hi @PierreBesson! @rzadp switfly made a PR with the upgrade, but none of us is well versed in the matter. Could you please review #225 and provide your input? 

We would appreciate it!

**Comment by PierreBesson** [comment]
I confirm that #225 fixes teleport on Westend and Rococo
