### ISSUE TITLE
Timeout exceeded

### ISSUE THREAD

**Issue by Tbaut** [paritytech/substrate-matrix-faucet#3]
from https://github.com/paritytech/devops/issues/664#issuecomment-721078538

This will help prevent many common issueswestend-faucet stops issuing coins: 

healthcheck url still responded with 200

on the pod:
/bot # wget -q -O - http://localhost:5555/health
Faucet backend is healthy

so the [this](https://github.com/paritytech/devops/issues/706#issue-737751524) did not help here.

it's something that hopefully can be fixed [here](https://github.com/paritytech/devops/issues/664)

server logfile:
```
Event sent to !cJFtAIkwxuofiSYkPN:matrix.org with event id $A5aodcV5FaGenOjzO-wA2_uavJ-LOJ53UMZuPIU8IKY
setting pendingEvent status to sent in !cJFtAIkwxuofiSYkPN:matrix.org
null { event_id: '$A5aodcV5FaGenOjzO-wA2_uavJ-LOJ53UMZuPIU8IKY' }
Already have event $A5aodcV5FaGenOjzO-wA2_uavJ-LOJ53UMZuPIU8IKY in limited sync - not resetting
(node:26) UnhandledPromiseRejectionWarning: Error: timeout of 10000ms exceeded
    at createError (/bot/node_modules/axios/lib/core/createError.js:16:15)
    at ClientRequest.handleRequestTimeout (/bot/node_modules/axios/lib/adapters/http.js:256:16)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at Socket.emitRequestTimeout (_http_client.js:662:40)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:440:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
(node:26) UnhandledPromiseRejectionWarning: Error: timeout of 10000ms exceeded
    at createError (/bot/node_modules/axios/lib/core/createError.js:16:15)
    at ClientRequest.handleRequestTimeout (/bot/node_modules/axios/lib/adapters/http.js:256:16)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at Socket.emitRequestTimeout (_http_client.js:662:40)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:440:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 44)
(node:26) UnhandledPromiseRejectionWarning: Error: timeout of 10000ms exceeded
    at createError (/bot/node_modules/axios/lib/core/createError.js:16:15)
    at ClientRequest.handleRequestTimeout (/bot/node_modules/axios/lib/adapters/http.js:256:16)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at Socket.emitRequestTimeout (_http_client.js:662:40)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:440:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
/sync error Error: Server returned 502 error
{ Error: Server returned 502 error
    at parseErrorResponse (/bot/node_modules/matrix-js-sdk/lib/http-api.js:818:15)
    at /bot/node_modules/matrix-js-sdk/lib/http-api.js:766:27
    at Request._callback (/bot/node_modules/matrix-js-sdk/lib/http-api.js:716:17)
    at Request.self.callback (/bot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/bot/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/bot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) httpStatus: 502 }
Number of consecutive failed sync requests: 1
Starting keep-alive
/sync error Error: Server returned 429 error
{ Error: Server returned 429 error
```

---

This seems to tell that when the faucet is sending an event to the Element server, it expects some answer (like a 200 I guess) but the call ends up timing out. This seems not to be related to the bot per se, but i can take a closer look when doing the unification.

**Comment by Tbaut** [comment]
This repo now has some more detailed errors, let's hope we can shed some light on that. This looks like the backend was not reachable..

**Comment by Tbaut** [comment]
Also from @lovelaced 

> This should probably be handled in some way by the code
```
(node:26) UnhandledPromiseRejectionWarning: Error: timeout of 10000ms exceeded
    at createError (/bot/node_modules/axios/lib/core/createError.js:16:15)
    at ClientRequest.handleRequestTimeout (/bot/node_modules/axios/lib/adapters/http.js:256:16)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at Socket.emitRequestTimeout (_http_client.js:662:40)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:440:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 180)
```

**Comment by Tbaut** [comment]
This is now handled, and the bot at least prints something in the chat "unexpected error occurred please check the logs". (and may ping you if you wish cf https://github.com/paritytech/substrate-matrix-faucet/issues/6)
Not sure why it happens though. Keeping this issue open to get back to it when it happens again.
