### ISSUE TITLE
westend-fauced stoped issuing tokens 

### ISSUE THREAD

**Issue by fevo1971** [paritytech/substrate-matrix-faucet#48]
westend server log:
```
[2021-03-05T08:34:08.921] [ERROR] default - ⭕ Oops, drip took more than 10000ms to answer
[2021-03-05T08:40:46.399] [INFO] default - 💸 sending tokens
2021-03-05 08:40:48        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction has a bad signature
[2021-03-05T08:40:48.509] [ERROR] default - ⭕ An error occured when sending tokens Error: 1010: Invalid Transaction: Transaction has a bad signature
    at RpcCoder._checkError (/backend/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)
    at RpcCoder.decodeResponse (/backend/node_modules/@polkadot/rpc-provider/coder/index.js:47:10)
    at HttpProvider.send (/backend/node_modules/@polkadot/rpc-provider/http/index.js:150:76)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async callWithRegistry (/backend/node_modules/@polkadot/rpc-core/index.js:261:20)
[2021-03-05T08:40:56.590] [ERROR] default - ⭕ Oops, drip took more than 10000ms to answer
pt/substrate-matrix-faucet - [main] » 2021-03-05T08:32:35.035] [ERROR] default - ⭕ Oops, drip took more than 10000ms to answer
[2021-03-05T08:33:58.909] [INFO] default - 💸 sending tokens
2021-03-05 08:34:01        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction has a bad signature
[2021-03-05T08:34:01.139] [ERROR] default - ⭕ An error occured when sending tokens Error: 1010: Invalid Transaction: Transaction has a bad signature
    at RpcCoder._checkError (/backend/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)
    at RpcCoder.decodeResponse (/backend/node_modules/@polkadot/rpc-provider/coder/index.js:47:10)
    at HttpProvider.send (/backend/node_modules/@polkadot/rpc-provider/http/index.js:150:76)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async callWithRegistry (/backend/node_modules/@polkadot/rpc-core/index.js:261:20)
[2021-03-05T08:34:08.921] [ERROR] default - ⭕ Oops, drip took more than 10000ms to answer
[2021-03-05T08:40:46.399] [INFO] default - 💸 sending tokens
2021-03-05 08:40:48        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction has a bad signature
[2021-03-05T08:40:48.509] [ERROR] default - ⭕ An error occured when sending tokens Error: 1010: Invalid Transaction: Transaction has a bad signature
    at RpcCoder._checkError (/backend/node_modules/@polkadot/rpc-provider/coder/index.js:84:13)
    at RpcCoder.decodeResponse (/backend/node_modules/@polkadot/rpc-provider/coder/index.js:47:10)
    at HttpProvider.send (/backend/node_modules/@polkadot/rpc-provider/http/index.js:150:76)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async callWithRegistry (/backend/node_modules/@polkadot/rpc-core/index.js:261:20)
[2021-03-05T08:40:56.590] [ERROR] default - ⭕ Oops, drip took more than 10000ms to answer
```

**Comment by lovelaced** [comment]
Can this be closed?

**Comment by lovelaced** [comment]
Apparently this is still an issue - it happened again yesterday with the newly deployed faucet. Required a restart of the pod to work again.

```
2021-03-27 22:24:15        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction has a bad signature
[2021-03-27T22:24:15.540] [ERROR] default - ⭕ An error occured when sending tokens Error: 1010: Invalid Transaction: Transaction has a bad signature
    at RpcCoder._checkError (/backend/node_modules/@polkadot/rpc-provider/coder/index.cjs:84:13)
    at RpcCoder.decodeResponse (/backend/node_modules/@polkadot/rpc-provider/coder/index.cjs:47:10)
    at HttpProvider.send (/backend/node_modules/@polkadot/rpc-provider/http/index.cjs:150:76)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async callWithRegistry (/backend/node_modules/@polkadot/rpc-core/index.cjs:252:20)
[2021-03-27T22:24:25.487] [ERROR] default - ⭕ Oops, drip took more than 10000ms to answer
```
