### ISSUE TITLE
Some !drips fail

### ISSUE THREAD

**Issue by lovelaced** [paritytech/substrate-matrix-faucet#51]
Some token requests to the faucet error and this is what's in the logs:

```
[2021-03-25T13:39:53.167] [ERROR] default - ⭕ An error occured when sending tokens Error: 1014: Priority is too low: (153452338088398 vs 153452338088398): The transaction has too low priority to replace another transaction already in the pool.
    at RpcCoder._checkError (/backend/node_modules/@polkadot/rpc-provider/coder/index.cjs:84:13)
    at RpcCoder.decodeResponse (/backend/node_modules/@polkadot/rpc-provider/coder/index.cjs:47:10)
    at HttpProvider.send (/backend/node_modules/@polkadot/rpc-provider/http/index.cjs:150:76)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async callWithRegistry (/backend/node_modules/@polkadot/rpc-core/index.cjs:252:20)
[2021-03-25T13:40:03.095] [ERROR] default - ⭕ Oops, drip took more than 10000ms to answer
```

I *suspect* this is due to more than one transaction being submitted within one block, but I'm not sure. This usually succeeds when the person tries the command again.

Tangentially, it would be better to have a friendlier, more descriptive message posted in chat than "please check the server logs". Normal people can't do that and it'd be better to print something more user-facing.

**Comment by lovelaced** [comment]
There's also another error I've seen recently:

```
2021-09-01 01:40:44        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction is outdated
[2021-09-01T01:40:44.586] [ERROR] default - ⭕ An error occured when sending tokens Error: 1010: Invalid Transaction: Transaction is outdated
    at RpcCoder._checkError (/backend/node_modules/@polkadot/rpc-provider/coder/index.cjs:84:13)
    at RpcCoder.decodeResponse (/backend/node_modules/@polkadot/rpc-provider/coder/index.cjs:47:10)
    at HttpProvider.send (/backend/node_modules/@polkadot/rpc-provider/http/index.cjs:150:76)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async callWithRegistry (/backend/node_modules/@polkadot/rpc-core/index.cjs:246:20)
```
