### ISSUE TITLE
Could not decode `MultiAddress`, variant doesn\'t exist

### ISSUE THREAD

**Issue by timorl** [paritytech/substrate-matrix-faucet#65]
I am trying to use the `server`/`backend` component and I stumbled into the following error:
```
[2021-06-17T16:23:05.988] [INFO] default - 💸 sending tokens
2021-06-17 16:23:06        RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: None, desc: "Could not decode `MultiAddress`, variant doesn\'t exist" } }): RuntimeApi, Execution failed: ApiError, FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: None, desc: \"Could not decode `MultiAddress`, variant doesn\\\'t exist\" } }
[2021-06-17T16:23:06.104] [ERROR] default - ⭕ An error occured when sending tokens Error: 1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: None, desc: "Could not decode `MultiAddress`, variant doesn\'t exist" } }): RuntimeApi, Execution failed: ApiError, FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: None, desc: \"Could not decode `MultiAddress`, variant doesn\\\'t exist\" } }
    at RpcCoder._checkError (/home/timorl/umienie/informatyka/aleph/substrate-matrix-faucet/node_modules/@polkadot/rpc-provider/coder/index.cjs:84:13)
    at RpcCoder.decodeResponse (/home/timorl/umienie/informatyka/aleph/substrate-matrix-faucet/node_modules/@polkadot/rpc-provider/coder/index.cjs:47:10)
    at HttpProvider.send (/home/timorl/umienie/informatyka/aleph/substrate-matrix-faucet/node_modules/@polkadot/rpc-provider/http/index.cjs:150:76)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async callWithRegistry (/home/timorl/umienie/informatyka/aleph/substrate-matrix-faucet/node_modules/@polkadot/rpc-core/index.cjs:246:20)
```

I found [this issue](https://github.com/polkascan/py-substrate-interface/issues/110), which seems to be about the same error in a very different context. Unfortunately I wasn't able to understand the discussion in that issue, so I'm not sure whether the solution from there applies to my problem, and even if it does I definitely don't know how to execute it.

I am sending these transactions to a custom chain. I know transactions sent by polkadot.js (between test accounts) work. Let me know what other information I should provide.

**Comment by timorl** [comment]
I keep digging, although I still hope someone will be able to help me. Some further findings (they are probably obvious to people familiar with substrate just by looking at the errors):

1. The error originates in `codec` decoding of `sp_runtime::MultiAddress`, complaining about a nonexistent variant.
2. Since the enum has never changed (afaict) the "nonexistent variant" is just a red herring – it is simply encoded wrong at the point of decoding.
3. I think I am using the JS side exactly the same way as the matrix bot is – if anyone wants to confirm that the code is [here](https://github.com/timorl/substrate-matrix-faucet/tree/page).
4. The other option is that something changed node-side – we are using substrate at [this commit](https://github.com/paritytech/substrate/commit/1fa8cf7cf9dbfe1b093b3e7e116dc3435c7f3f7b).

I still suspect this is mostly me missing some configuration option somewhere or something silly like that, but I am running out of ideas as to how to find it.

**Comment by NukeManDan** [comment]
I figure you are running into issues with this new type that is used in the context of parachains - the bot might not be compliamt with that yet (substrate upstream)

you might need to update the api: https://github.com/paritytech/substrate-matrix-faucet#misc
using the latest JS API avalible stuff.

**Comment by timorl** [comment]
Thanks @NukeManDan, the second hint helped me find the problem!

As expected, this was just me being... less than smart. I copied the example `.env` file for the bot, only changing variables I knew how to change. This meant I left the `INJECTED_TYPES="{ "Address": "AccountId", "LookupSource": "AccountId" }"` line in. But this injected non-default types for addresses, hence the error. After removing this line everything works brilliantly.
